### PR TITLE
Fixed flip clock displaying 60 seconds instead of 0 and minutes flipping a second too soon on countdown

### PR DESCRIPTION
**Pull request by PLPeeters**
Fixed flip clock displaying 60 seconds instead of 0 and minutes flipping a second too soon on countdown.

### CODE REVIEW

**Comment by PLPeeters** [comment]
Just noticed my latest commit was also added to this pull request automatically, sorry about that. I'm not really experienced with pull requests, so is it possible for you to exclude that one (in case you don't want it) or do you want me to rollback that commit?

**Comment by objectivehtml** [comment]
I like these changes. I need to do some testing before I implement these. (I actually need to implement unit testing for these components). Thanks for the pull request though, nice job.

**Comment by objectivehtml** [comment]
I just refactored the entire library last night in prep for the official v1 release. I improved many aspects of the code, so I need to test this new version to see if this problem even exists. If you get a chance and want to test it out, grab the new dev branch and see if the code is still problematic. And if so, one of us will have to rework these changes into the new code because it's not going to be possible to merge at this point.

**Comment by PLPeeters** [comment]
I just did a quick test, and the first thing I noticed is that the clock isn't counting down, despite the fact I set `countdown` to `true`. I did see a 60 when it counted up though, so it looks like the bug is still in there.

**Comment by objectivehtml** [comment]
The latest changes were breaking to the API. I haven't documented these changes yet. 

You should do this. Notice the new `clockFaceOptions` parameter. Options like `countdown` are no longer associated with the `FlipClock.Factory` classes and instead belong to the `FlipClock.Face` class. This makes things a lot better in the long run for the API.

	clock = new FlipClock($('.clock'), 359998, {
	    clockFace: 'HourlyCounter',
	    clockFaceOptions: {
	    	countdown: true
	    }
	});

**Comment by objectivehtml** [comment]
What clock face are you using? Can you post your code for me?

**Comment by PLPeeters** [comment]
Was planning to do so, I'm just finishing up the tests I can think of :-) I'll post the code ASAP, shouldn't be long.

I'm currently using the `DailyCounter` face.

**Comment by PLPeeters** [comment]
And here you go: <https://gist.github.com/PLPeeters/abff282a108d5fa9a509>

The 60 displays both when counting up and counting down apparently. Also looks like it's briefly displaying 69 instead of 59 afterwards when it's a countdown.

**Comment by objectivehtml** [comment]
This stuff should be fixed in the master branch now, just FYI. Thanks taking the time to compile these examples.

**Comment by objectivehtml** [comment]
Also, `clock.setTime()` and `clock.getTime()` where changes to `clock.setFaceValue()` and `clock.getFaceValue()`. I changed this because `setTime()` implies each clock face requires a time, which is not the case. The new alphabetical clock face and the counter clock face both don't require any "time", so this method was not accurately named.

**Comment by PLPeeters** [comment]
You're welcome. I can confirm it's indeed fixed in the `dev` branch. Setting the face value from a `Date` object is still not possible though, but I guess that's normal for now.

**Comment by objectivehtml** [comment]
Use a `Date`object is possible with some clock faces. The reason the counter clock faces don't support date objects is because they are "counters". So they start with an integer, and either count up or down. If a `Date` is passed, how would the integer be calculated (for example)? I just didn't see an applicable use for integrating the dates properly given counter work around integers.

**Comment by PLPeeters** [comment]
It makes sense for clocks that count down to a certain moment or up from a certain moment, which I think is a pretty common use case for this type of library.

If you look at my tests, I have to subtract `now.getTime()` and then divide by 1000 just to get the time for my countdown, making the code a bit harder to understand. Passing the `Date` I want to count down to would be much easier. The same goes for counting up.

The needed integer would be calculated just like in my example. It would look something like this:

~~~
setFaceValue: function(value) {
	if (value instanceof Date) {
		var now = new Date();
		
		if (this.countdown) {
			this.face.setValue(Math.floor((value.getTime() - now.getTime()) / 1000));
		} else {
			this.face.setValue(Math.floor((now.getTime() - value.getTime()) / 1000));
		}
	} else {
		this.face.setValue(value);
	}

	return this;
}
~~~

Maybe this should be in the `setValue()` function of the clock face directly, I'm not quite sure about that.

**Comment by objectivehtml** [comment]
`clock.setFaceValue` is just an alias to `clock.face.setValue` for convenience, so it's essentially doing the same thing. If I were to add that logic, it would be indeed to the clock face itself. I will look into this code a bit more and see if it makes sense to integrate into the library. Basically just want to make sure it doesn't break other clock faces, or just cause clock faces to constantly have to override the behavior.

**Pull request closed without merging**
